nohup: ignoring input
INFO:root:Бот запущен
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getMe "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/deleteWebhook "HTTP/1.1 200 OK"
INFO:telegram.ext.Application:Application started
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/sendMessage "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/sendMessage "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 409 Conflict"
ERROR:telegram.ext.Updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.Application:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 715, in _network_loop_retry
    if not await action_cb():
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 384, in polling_action_cb
    raise exc
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 618, in get_updates
    updates = await super().get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 542, in decorator
    result = await func(self, *args, **kwargs)
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 4164, in get_updates
    await self._post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 630, in _post
    return await self._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 658, in _do_post
    return await request.post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 409 Conflict"
ERROR:telegram.ext.Updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.Application:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 715, in _network_loop_retry
    if not await action_cb():
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 384, in polling_action_cb
    raise exc
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 618, in get_updates
    updates = await super().get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 542, in decorator
    result = await func(self, *args, **kwargs)
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 4164, in get_updates
    await self._post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 630, in _post
    return await self._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 658, in _do_post
    return await request.post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 409 Conflict"
ERROR:telegram.ext.Updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.Application:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 715, in _network_loop_retry
    if not await action_cb():
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 384, in polling_action_cb
    raise exc
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 618, in get_updates
    updates = await super().get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 542, in decorator
    result = await func(self, *args, **kwargs)
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 4164, in get_updates
    await self._post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 630, in _post
    return await self._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 658, in _do_post
    return await request.post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 409 Conflict"
ERROR:telegram.ext.Updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.Application:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 715, in _network_loop_retry
    if not await action_cb():
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 384, in polling_action_cb
    raise exc
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 618, in get_updates
    updates = await super().get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 542, in decorator
    result = await func(self, *args, **kwargs)
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 4164, in get_updates
    await self._post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 630, in _post
    return await self._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 658, in _do_post
    return await request.post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 409 Conflict"
ERROR:telegram.ext.Updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.Application:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 715, in _network_loop_retry
    if not await action_cb():
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 384, in polling_action_cb
    raise exc
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 618, in get_updates
    updates = await super().get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 542, in decorator
    result = await func(self, *args, **kwargs)
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 4164, in get_updates
    await self._post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 630, in _post
    return await self._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 658, in _do_post
    return await request.post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 409 Conflict"
ERROR:telegram.ext.Updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.Application:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 715, in _network_loop_retry
    if not await action_cb():
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 384, in polling_action_cb
    raise exc
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 618, in get_updates
    updates = await super().get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 542, in decorator
    result = await func(self, *args, **kwargs)
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 4164, in get_updates
    await self._post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 630, in _post
    return await self._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 658, in _do_post
    return await request.post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 409 Conflict"
ERROR:telegram.ext.Updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.Application:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 715, in _network_loop_retry
    if not await action_cb():
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 384, in polling_action_cb
    raise exc
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 618, in get_updates
    updates = await super().get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 542, in decorator
    result = await func(self, *args, **kwargs)
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 4164, in get_updates
    await self._post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 630, in _post
    return await self._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 658, in _do_post
    return await request.post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 409 Conflict"
ERROR:telegram.ext.Updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.Application:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 715, in _network_loop_retry
    if not await action_cb():
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 384, in polling_action_cb
    raise exc
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 618, in get_updates
    updates = await super().get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 542, in decorator
    result = await func(self, *args, **kwargs)
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 4164, in get_updates
    await self._post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 630, in _post
    return await self._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 658, in _do_post
    return await request.post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 409 Conflict"
ERROR:telegram.ext.Updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.Application:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 715, in _network_loop_retry
    if not await action_cb():
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 384, in polling_action_cb
    raise exc
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 618, in get_updates
    updates = await super().get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 542, in decorator
    result = await func(self, *args, **kwargs)
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 4164, in get_updates
    await self._post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 630, in _post
    return await self._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 658, in _do_post
    return await request.post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 409 Conflict"
ERROR:telegram.ext.Updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.Application:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 715, in _network_loop_retry
    if not await action_cb():
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 384, in polling_action_cb
    raise exc
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 618, in get_updates
    updates = await super().get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 542, in decorator
    result = await func(self, *args, **kwargs)
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 4164, in get_updates
    await self._post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 630, in _post
    return await self._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 658, in _do_post
    return await request.post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 409 Conflict"
ERROR:telegram.ext.Updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.Application:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 715, in _network_loop_retry
    if not await action_cb():
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 384, in polling_action_cb
    raise exc
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 618, in get_updates
    updates = await super().get_updates(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 542, in decorator
    result = await func(self, *args, **kwargs)
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 4164, in get_updates
    await self._post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 630, in _post
    return await self._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/_bot.py", line 658, in _do_post
    return await request.post(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "/root/informer_ass/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7953491746:AAEcULVXG_I1lgWdOXRqGCOdx5DMBI98hLE/getUpdates "HTTP/1.1 200 OK"
INFO:telegram.ext.Application:Application is stopping. This might take a moment.
INFO:telegram.ext.Application:Application.stop() complete
